name: CI

on:
  push:
    branches: [main]

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-python@v4

      - uses: actions/checkout@v3
      - name: build
        run: make && make clean && make fclean && make re

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: install pytest
        run: pip install -U pytest

      - uses: actions/checkout@v3
      - name: Run tests with pytest
        run: make tests_run
